const $ = id => document.getElementById(id);
async function activeTab(){const tabs=await chrome.tabs.query({active:true,lastFocusedWindow:true});const tab=tabs[0];if(!tab?.id||!/^https:\/\/www\.fiverr\.com\//.test(tab.url||''))throw new Error('Open a Fiverr page first.');return tab}
async function send(type,payload={}){const tab=await activeTab();const res=await chrome.tabs.sendMessage(tab.id,{type,payload});if(res?.error)throw new Error(res.error);return res}
function show(id,text,bad=false){const e=$(id);e.style.display='block';e.textContent=text;e.className='result '+(bad?'bad':'')}
function status(id,text,bad=false){$(id).textContent=text;$(id).className='status '+(bad?'bad':'ok')}
async function ai(prompt,system='You are a practical Fiverr marketplace assistant. Return concise, actionable output.'){const r=await chrome.runtime.sendMessage({type:'AI_REQUEST',payload:{prompt,systemPrompt:system,temperature:.6}});if(r?.error)throw new Error(r.error);return r.result}
async function load(){const s=await chrome.storage.local.get(['bbWatcherEnabled','bbWatchInterval','bbStopOnChange']);$('watchInterval').value=String(s.bbWatchInterval||60);$('stopOnChange').value=String(s.bbStopOnChange!==false);$('watchBtn').textContent=s.bbWatcherEnabled?'Stop watcher':'Start watcher';status('watchStatus',s.bbWatcherEnabled?'Watcher is enabled on the current Fiverr tab.':'Watcher is off.')}
$('watchBtn').onclick=async()=>{const s=await chrome.storage.local.get('bbWatcherEnabled');const enabled=!s.bbWatcherEnabled;await chrome.storage.local.set({bbWatcherEnabled:enabled,bbWatchInterval:Number($('watchInterval').value),bbStopOnChange:$('stopOnChange').value==='true'});$('watchBtn').textContent=enabled?'Stop watcher':'Start watcher';status('watchStatus',enabled?'Watcher enabled. Keep the Fiverr tab open.':'Watcher stopped.');try{await send('BB_WATCH_CONFIG')}catch{}};
$('watchInterval').onchange=()=>chrome.storage.local.set({bbWatchInterval:Number($('watchInterval').value)});$('stopOnChange').onchange=()=>chrome.storage.local.set({bbStopOnChange:$('stopOnChange').value==='true'});
$('scanBtn').onclick=async()=>{try{const r=await send('BB_SCAN_PAGE');let out=`Found ${r.gigs.length} visible gigs.\n\n`;out+=r.gigs.slice(0,20).map((g,i)=>`${i+1}. ${g.title}\n   ${g.price?'$'+g.price:'Price unknown'} · ${g.reviews||0} reviews · ${g.rating||'—'} rating · Opportunity ${g.score}/100`).join('\n');show('scanResult',out)}catch(e){show('scanResult',e.message,true)}};
$('keywordBtn').onclick=async()=>{try{const r=await send('BB_KEYWORDS');show('keywordResult',r.terms.length?`Top recurring terms:\n\n${r.terms.map((x,i)=>`${i+1}. ${x.term} · ${x.count} appearances · ${x.signal}`).join('\n')}`:'No useful terms found. Open a Fiverr search results page.',!r.terms.length)}catch(e){show('keywordResult',e.message,true)}};
$('healthBtn').onclick=async()=>{try{const r=await send('BB_GIG_HEALTH');show('healthResult',`Gig health: ${r.score}/100\n\n${r.breakdown.map(x=>`${x.name}: ${x.score}/100 — ${x.note}`).join('\n')}`)}catch(e){show('healthResult',e.message,true)}};
$('pricingBtn').onclick=async()=>{try{const r=await send('BB_SCAN_PAGE');const prices=r.gigs.map(g=>g.price).filter(Number.isFinite).sort((a,b)=>a-b);if(!prices.length)throw new Error('No visible prices found. Open a Fiverr search page.');const mid=prices[Math.floor(prices.length/2)],min=prices[0],max=prices.at(-1);show('pricingResult',`Visible market sample: ${prices.length} gigs\nLow: $${min}\nMedian: $${mid}\nHigh: $${max}\n\nSuggested starting range: $${Math.max(5,Math.round(mid*.8))}–$${Math.round(mid*1.25)}\n\nUse the median as an anchor, then price higher when your offer has a clear differentiator.`)}catch(e){show('pricingResult',e.message,true)}};
$('wizardBtn').onclick=async()=>{try{const niche=$('wizardNiche').value.trim();if(!niche)throw new Error('Describe the service first.');const r=await ai(`Build a complete Fiverr gig for this service: ${niche}. Return: TITLE, CATEGORY, 5 TAGS, DESCRIPTION, three packages with prices and deliverables, 5 FAQs, BUYER REQUIREMENTS, and a THUMBNAIL BRIEF. Make every claim defensible. Never invent credentials, reviews, client results or certifications. Keep it specific to the service, buyer and outcome.`);show('wizardResult',r)}catch(e){show('wizardResult',e.message,true)}};
$('thumbBtn').onclick=async()=>{try{const p=await send('BB_PAGE_CONTEXT');const r=await ai(`Create 3 Fiverr thumbnail concepts for this gig. Give each a short headline, visual hierarchy, composition, proof element and image generation prompt. Avoid fake logos, fake reviews and misleading claims.\n\nCurrent gig/page context:\n${JSON.stringify(p).slice(0,12000)}`);show('thumbResult',r)}catch(e){show('thumbResult',e.message,true)}};
$('optimiseBtn').onclick=async()=>{try{const p=await send('BB_PAGE_CONTEXT');const goal=$('optimiseGoal').value.trim()||'increase clicks and qualified enquiries';const r=await ai(`Optimise this Fiverr gig for ${goal}. Return: 1) improved title, 2) improved description, 3) 5 tag suggestions, 4) package/pricing positioning, 5) 5 FAQs, 6) three specific changes and why. Never invent credentials, results or tools.\n\nPage context:\n${JSON.stringify(p).slice(0,16000)}`);show('optimiseResult',r)}catch(e){show('optimiseResult',e.message,true)}};
$('saveDraft').onclick=async()=>{try{const r=await send('BB_SAVE_DRAFT');status('draftStatus',`Draft saved locally: ${r.count} fields.`)}catch(e){status('draftStatus',e.message,true)}};
$('restoreDraft').onclick=async()=>{try{const r=await send('BB_RESTORE_DRAFT');status('draftStatus',`Restored ${r.count} fields.`)}catch(e){status('draftStatus',e.message,true)}};
$('addCompetitor').onclick=async()=>{try{const r=await send('BB_PAGE_CONTEXT');if(!r.url.includes('/gigs/'))throw new Error('Open a specific Fiverr gig first.');const existing=(await chrome.storage.local.get('bbCompetitors')).bbCompetitors||[];const old=existing.find(x=>x.url===r.url);const item={url:r.url,title:r.title,description:r.description,price:r.price,fp:r.fingerprint,checkedAt:Date.now()};if(old){const changed=old.fp!==item.fp;const next=existing.map(x=>x.url===item.url?item:x);await chrome.storage.local.set({bbCompetitors:next});show('competitorResult',changed?`Changed since last snapshot.\n\nPrevious title: ${old.title||'—'}\nCurrent title: ${item.title||'—'}\n\nSnapshot updated.`:'No change detected. Snapshot refreshed.')}else{existing.unshift(item);await chrome.storage.local.set({bbCompetitors:existing.slice(0,50)});show('competitorResult','Competitor added to your local watch list. Revisit it and run this again to compare changes.')}}catch(e){show('competitorResult',e.message,true)}};
load();